CREATE TABLE [dbo].[CLIENTE] (
    [ID]          UNIQUEIDENTIFIER NOT NULL,
    [NOME]        VARCHAR (300)    NOT NULL,
    [CPF]         VARCHAR (300)    NOT NULL,
    [CNPJ]        VARCHAR (300)    NOT NULL,
    [ENDERECO]    VARCHAR (300)    NOT NULL,
    [CNH]         VARCHAR (300)    NOT NULL,
    [TELEFONE]    VARCHAR (300)    NOT NULL,
    [TIPOCLIENTE] INT              NOT NULL,
    [EMAIL]       VARCHAR (300)    NOT NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

