CREATE TABLE [dbo].[VEICULO] (
    [ID]                 UNIQUEIDENTIFIER NOT NULL,
    [MODELO]             VARCHAR (300)    NOT NULL,
    [MARCA]              VARCHAR (300)    NOT NULL,
    [ANO]                INT              NOT NULL,
    [COR]                VARCHAR (300)    NOT NULL,
    [PLACA]              VARCHAR (300)    NOT NULL,
    [KMPERCORRIDO]       FLOAT (53)       NOT NULL,
    [TIPODECOMBUSTIVEL]  VARCHAR (300)    NOT NULL,
    [CAPACIDADEDOTANQUE] FLOAT (53)       NOT NULL,
    [GRUPO_ID]           UNIQUEIDENTIFIER NOT NULL,
    [FOTO]               VARBINARY (MAX)  NOT NULL,
    CONSTRAINT [PK_VEICULO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_VEICULO_GRUPO] FOREIGN KEY ([GRUPO_ID]) REFERENCES [dbo].[GRUPODEVEICULOS] ([ID])
);

